### PR TITLE
Avoid using Pathname to compute relative paths in spout - fix merge regression

### PR DESCRIPTION
**Pull request by robbavey**
Merge inadvertently changed inherited method to once again use
Pathname to compute relative paths. This change once more allows
the code to work either in a jar context, or a .rb file on
the filesystem.

### CODE REVIEW

**Comment by rtyler** [comment]
@robbavey I doubt this was already covered by a unit test, but would it be too much to ask to add one to cover this regression? If not, NBD

**Comment by robbavey** [comment]
OK - will take a look and see if I can up with something worthwhile.

**Comment by rtyler** [comment]
Cool!

**Comment by rtyler** [comment]
This has been tagged for 0.8.1 which will be released in the next few minutes provided travis passes

**Pull request merged**
